import 'package:flutter/material.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedRectangle2Widget12.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedRectangle2Widget22.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedIc_black_closeWidget.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedRectangle2Widget18.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedEllipseWidget.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedRectangle2Widget16.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedRectangle2Widget20.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedRectangle2Widget14.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedMyPhotosWidget.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedBritisharchitectwhosecompanyFosterPartnersmaintainsanin.dart';
import 'package:flutterapp/unsplashtestapp/generatedprofilewidget/generated/GeneratedNormanFosterWidget.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 97.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 63.0,
                child:
                    GeneratedBritisharchitectwhosecompanyFosterPartnersmaintainsanin(),
              ),
              Positioned(
                left: 96.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 57.0,
                child: GeneratedNormanFosterWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 63.0,
                child: GeneratedEllipseWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 50.0,
                child: GeneratedMyPhotosWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 218.0,
                child: GeneratedRectangle2Widget12(),
              ),
              Positioned(
                left: 23.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 218.0,
                child: GeneratedRectangle2Widget14(),
              ),
              Positioned(
                left: 200.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 218.0,
                child: GeneratedRectangle2Widget16(),
              ),
              Positioned(
                left: 201.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 218.0,
                child: GeneratedRectangle2Widget18(),
              ),
              Positioned(
                left: 24.0,
                top: 779.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 218.0,
                child: GeneratedRectangle2Widget20(),
              ),
              Positioned(
                left: 201.0,
                top: 805.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 218.0,
                child: GeneratedRectangle2Widget22(),
              ),
              Positioned(
                left: 26.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedIc_black_closeWidget(),
              )
            ]),
      ),
    ));
  }
}
